name: Super-Linter

on: [pull_request]

jobs:
  build:
    name: Run Super-Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: github/super-linter@v8.3.2
        env:
          ERROR_ON_MISSING_EXEC_BIT: true
          VALIDATE_EDITORCONFIG: true
          VALIDATE_YAML: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
