name: Lint

on: [pull_request]

jobs:
  build:
    name: GitHub Super-Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: super-linter/super-linter@v7.2.1
        env:
          ERROR_ON_MISSING_EXEC_BIT: true
          VALIDATE_EDITORCONFIG: true
          VALIDATE_YAML: true
          VALIDATE_BIOME: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
