name: Super-Linter

on: [pull_request]

jobs:
  build:
    name: Run Super-Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          persist-credentials: false
      - uses: super-linter/super-linter@v8.3.2
        env:
          ERROR_ON_MISSING_EXEC_BIT: true
          VALIDATE_EDITORCONFIG: true
          VALIDATE_YAML: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
