name: Lint

on: [pull_request]

jobs:
  build:
    name: GitHub Super-Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v4.6.0
        env:
          ERROR_ON_MISSING_EXEC_BIT: true
          VALIDATE_EDITORCONFIG: true
          VALIDATE_YAML: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
